# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phonestrument
email: motekulo@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
        Simple open source music production for Android
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://motekulo.github.io/phonestrument" # the base hostname & protocol for your site
twitter_username: deniscrowdy
github_username:  motekulo

# Build settings
markdown: kramdown
